version: "3.9"

services:
  angualar:
    container_name: angularapp
    image: 'node:16'
    working_dir: /app
    command:
      - /bin/sh
      - '-c'
      - 'npm install && node_modules/.bin/ng serve --host 0.0.0.0'
    ports:
      - 4200:4200
    volumes:
      - ./:/app/
